### ISSUE TITLE
pyproject.toml settings should use the [tool] table

### ISSUE THREAD

**Issue by ivanlonel** [opengisch/qgis-plugin-ci#242]
The build dependency declaration specification requires third-party tools to use the namespace `tool.*` in pyproject.toml, as defined in [PEP518](https://peps.python.org/pep-0518/#tool-table).

As such, qgis-plugin-ci settings should be under `[tool.qgis-plugin-ci]`, not `[qgis-plugin-ci]` as it is now.

Example:
```toml
[tool.bandit]
skips = ["B405", "B410"]

[tool.black]
line-length = 119

[tool.isort]
line_length = 119

[tool.mypy]
show_column_numbers = true

[tool.qgis-plugin-ci]
plugin_path = "qgis_plugin_ci_testing"
github_organization_slug = "opengisch"
project_slug = "qgis-plugin-ci"
```
