### ISSUE TITLE
The .qm translation file is not sent when I publish my plugin

### ISSUE THREAD

**Issue by florentfgrs** [opengisch/qgis-plugin-ci#256]
### I use version 2.8.1 of qgis-plugin-ci

In my plugin, I've generated my translation files, so I have a .qm file in `my_plugin/resources/i18n`

### I run the package command : 

```
qgis-plugin-ci package latest --allow-uncommitted-changes --plugin-repo-url $REPO_PLUGIN_URL
```

It's ok, I still have my .qm files in `my_pluin/resources/i18n`. 
Event it's also working on the CI job, see my .qm file in the [release](https://gitlab.com/Oslandia/qgis/qwc2_tools/-/releases) and also in the [gitlab pages repo ](https://oslandia.gitlab.io/qgis/qwc2_tools.0.5.0-beta1.zip)

### I have the .qm in my gitignore so I'm modifying this one. 

```shell
sed -i "s|^*.qm.*| |" .gitignore
git add $PROJECT_FOLDER/
```
I see my file in [logs](https://gitlab.com/Oslandia/qgis/qwc2_tools/-/jobs/5626148894#L353)  

### After that, I run my command line : 

```shell
qgis-plugin-ci -vv release v0.5.0-beta1 --allow-uncommitted-changes --osgeo-username my_username --osgeo-password my_pass
```

The command runs without a problem, but in the plugin that has been published I can't find my `.qm` translation files in  `my_pluin/resources/i18n`

It seems that my files are not being sent when I upload them.

:warning: If you go to the QGIS plugin directory you'll see my .qm but that's because I uploaded it manually.

### Link 

- [My project ](https://gitlab.com/Oslandia/qgis/qwc2_tools)

### Executed in gitlab CI 

[Entire CI ](https://gitlab.com/Oslandia/qgis/qwc2_tools/-/blob/main/.gitlab-ci.yml?ref_type=heads)

```yml
deploy:qgis-repository:
  stage: 🚀 deploy
  image: python:3.11
  tags:
    - docker
  rules:
    # on a tag
    - if: $CI_COMMIT_TAG
  needs:
    - job: build:translation
      artifacts: true
  before_script:
    - apt install git
    - python -m pip install -U -r requirements/packaging.txt
  script:
    # list files
    # Temporary fix : copy license file to plugin folder
    - cp ./LICENSE ./${PROJECT_FOLDER}/LICENSE
    - ls -lR
    # print some info
    - echo "Deploying the version ${CI_COMMIT_TAG} plugin to QGIS Plugins Repository with the user ${OSGEO_USER_NAME}"
    - python ${PROJECT_FOLDER}/__about__.py

    # Amend gitignore to include translation
    - sed -i "s|^*.qm.*| |" .gitignore

    # git tracks new files
    - git add $PROJECT_FOLDER/

    # release it
    - qgis-plugin-ci -vv release ${CI_COMMIT_TAG}
      --allow-uncommitted-changes
      --osgeo-username $OSGEO_USER_NAME
      --osgeo-password $OSGEO_USER_PASSWORD
```
