### ISSUE TITLE
uploading to plugins.qgis.org

### ISSUE THREAD

**Issue by Gustry** [opengisch/qgis-plugin-ci#3]
I'm starting to setup this tool on some for now. it looks cool ;-)

I have tested only the `release` command. I got everything working on local for releasing the zip on plugins.qgis.org. But I can't get it to work on travis:

On travis:

```
        - provider: script
          script: qgis-plugin-ci release ${TRAVIS_TAG} --github-token ${GH_TOKEN} --osgeo-username ${OSGEO_USERNAME} --osgeo-password {OSGEO_PASSWORD} --create-plugin-repo
          on:
            tags: true
```
```
GitRelease(title="Release of 3.2.9") 3.2.9 https://uploads.github.com/repos/3liz/lizmap-plugin/releases/24176879/assets{?name,label}

Uploading asset: /tmp/tmpc4tiipmh.xml as plugins.xml

OK

A protocol error occurred

URL: Gustry:******@plugins.qgis.org:443/plugins/RPC2/

HTTP/HTTPS headers: {'Date': 'Tue, 03 Mar 2020 15:59:53 GMT', 'Server': 'nginx/1.4.7', 'Content-Type': 'text/html; charset=utf-8', 'Vary': 'Cookie', 'Content-Encoding': 'gzip', 'Transfer-Encoding': 'chunked'}

Error code: 403

Error message: FORBIDDEN

No stash entries found.
```

If I copy/paste this line on my terminal, it works.
I tried to put my login and osgeo password not encrypted on travis. It didn't work too. (I went to change my password don't worry ;-) )

Do you have any idea? Does it work for you from travis?
