### ISSUE TITLE
Include output from actual upload / properly error on issue (`no public version gets uploaded`)

### ISSUE THREAD

**Issue by olivierdalang** [opengisch/qgis-plugin-ci#81]
Hi !

For some reason, in my github workflow, the commands succeeds, but no version gets actually uploaded to the repository (https://plugins.qgis.org/plugins/qdmtk/ shows `This plugin has no public version yet.`). Note that the credentials are OK as it created the plugin.

I think we should include output from the actual upload to help debug if there's any issue, and also ensure we exit with an error code in case of issues.

Extract of the github workflow yaml:
```
      - name: Install qgis-plugin-ci
        run: pip install qgis-plugin-ci==2.0.1

      - name: Deploy to QGIS plugin repository
        env:
          OSGEO_USERNAME: ${{ secrets.OSGEO_USERNAME }}
          OSGEO_PASSWORD: ${{ secrets.OSGEO_PASSWORD }}
        run: qgis-plugin-ci release --osgeo-username "$OSGEO_USERNAME" --osgeo-password "$OSGEO_PASSWORD" "${GITHUB_REF##*/v}"
```

Output of the github workflow:
```
Run qgis-plugin-ci release --osgeo-username "$OSGEO_USERNAME" --osgeo*** "${GITHUB_REF##*/v}"
  qgis-plugin-ci release --osgeo-username "$OSGEO_USERNAME" --osgeo*** "${GITHUB_REF##*/v}"
  shell: /bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.9.5/x64
    OSGEO_USERNAME: ***
    OSGEO_PASSWORD: ***
*** is pre-release: YES
archive plugin with stash: 99ec29759459ed744cf06c56e71c92fb4b112f96
No items found in qdmtk/*.qrc
-------
files in ZIP archive (qdmtk.0.0.1-alpha.2.zip):
qdmtk/__init__.py
qdmtk/exceptions.py
qdmtk/icon.svg
qdmtk/icon_dj.svg
qdmtk/icon_pg.svg
qdmtk/metadata.txt
qdmtk/plugin.py
qdmtk/provider.py
qdmtk/qdmtkdemo/__init__.py
qdmtk/qdmtkdemo/config.py
qdmtk/qdmtkdemo/migrations/0001_initial.py
qdmtk/qdmtkdemo/migrations/0002_data.py
qdmtk/qdmtkdemo/migrations/__init__.py
qdmtk/qdmtkdemo/models.py
qdmtk/requirements.txt
qdmtk/router.py
qdmtk/utils.py
qdmtk/version.py
-------
archive plugin with stash: 614379341b97706c8956a0cff786643692a07634
No items found in qdmtk/*.qrc
-------
files in ZIP archive (qdmtk-experimental.0.0.1-alpha.2.zip):
qdmtk/__init__.py
qdmtk/exceptions.py
qdmtk/icon.svg
qdmtk/icon_dj.svg
qdmtk/icon_pg.svg
qdmtk/metadata.txt
qdmtk/plugin.py
qdmtk/provider.py
qdmtk/qdmtkdemo/__init__.py
qdmtk/qdmtkdemo/config.py
qdmtk/qdmtkdemo/migrations/0001_initial.py
qdmtk/qdmtkdemo/migrations/0002_data.py
qdmtk/qdmtkdemo/migrations/__init__.py
qdmtk/qdmtkdemo/models.py
qdmtk/requirements.txt
qdmtk/router.py
qdmtk/utils.py
qdmtk/version.py
-------
Plugin ID: 2449
Version ID: 12260
```
